AWSTemplateFormatVersion: "2010-09-09"
Description: Cfn sample Network Stack

Parameters:
  VpcName:
    Type: String
    Description: Name of the VPC
  VpcCidr:
    Type: String
    Description: CIDR block for the VPC
  SubnetName1:
    Type: String
    Description: Name of the first subnet
  SubnetName2:
    Type: String
    Description: Name of the second subnet
  SubnetName3:
    Type: String
    Description: Name of the third subnet
  SubnetCidr1:
    Type: String
    Description: CIDR block for the first subnet
  SubnetCidr2:
    Type: String
    Description: CIDR block for the second subnet
  SubnetCidr3:
    Type: String
    Description: CIDR block for the third subnet
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket containing the templates

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cfn-nested-sample.s3.ap-northeast-1.amazonaws.com/network/vpc.yaml"
      Parameters:
        VpcCidr: !Ref VpcCidr

  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cfn-nested-sample.s3.ap-northeast-1.amazonaws.com/network/subnet.yaml"
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SubnetCidr1: !Ref SubnetCidr1
        SubnetCidr2: !Ref SubnetCidr2
        SubnetCidr3: !Ref SubnetCidr3

Outputs:
  VpcId:
    Description: The ID of the VPC
    Value: !GetAtt VPCStack.Outputs.VpcId

  SubnetId1:
    Description: The ID of the first Subnet
    Value: !GetAtt SubnetStack.Outputs.SubnetId1

  SubnetId2:
    Description: The ID of the second Subnet
    Value: !GetAtt SubnetStack.Outputs.SubnetId2

  SubnetId3:
    Description: The ID of the third Subnet
    Value: !GetAtt SubnetStack.Outputs.SubnetId3
